import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
    faServer,
    faDesktop,
    faLaptop,
    faTerminal,
    faDatabase,
    faCloud,
    faLock,
    faNetworkWired,
    faHardDrive,
    faMicrochip,
    faCube,
    faCodeBranch,
    faRobot,
    faBrain,
    faFire,
    faGlobe,
    faShield,
    faBolt,
    faWifi,
    faCode,
    faLayerGroup,
    faFlask,
    faSatelliteDish,
    faGamepad,
    faCamera,
    faMusic,
    faVideo,
    faToolbox,
    faWrench,
    faCogs,
    faBox,
} from "@fortawesome/free-solid-svg-icons";
import {
    faLinux,
    faDocker,
    faPython,
    faRust,
    faGolang,
    faNodeJs,
} from "@fortawesome/free-brands-svg-icons";

export const ICON_MAP: Record<string, IconDefinition> = {
    server: faServer,
    desktop: faDesktop,
    laptop: faLaptop,
    terminal: faTerminal,
    database: faDatabase,
    cloud: faCloud,
    lock: faLock,
    network: faNetworkWired,
    "hard-drive": faHardDrive,
    microchip: faMicrochip,
    cube: faCube,
    "code-branch": faCodeBranch,
    robot: faRobot,
    brain: faBrain,
    fire: faFire,
    globe: faGlobe,
    shield: faShield,
    bolt: faBolt,
    wifi: faWifi,
    code: faCode,
    layers: faLayerGroup,
    flask: faFlask,
    satellite: faSatelliteDish,
    gamepad: faGamepad,
    camera: faCamera,
    music: faMusic,
    video: faVideo,
    toolbox: faToolbox,
    wrench: faWrench,
    cogs: faCogs,
    box: faBox,
    linux: faLinux,
    docker: faDocker,
    python: faPython,
    rust: faRust,
    golang: faGolang,
    nodejs: faNodeJs,
};

export function getIcon(name: string | null | undefined): IconDefinition {
    if (name && ICON_MAP[name]) return ICON_MAP[name];
    return faTerminal;
}
